server:
  port: 8085
  servlet:
    context-path: /api
keycloak:
  client-id: auth-service-v1
  client-secret: client_secret
  get-token-url: http://localhost:8080/realms/PowerRanger/protocol/openid-connect/token
  issuer-url: http://localhost:8080/realms/PowerRanger
redis:
  config:
    cache:
      host: localhost
      port: 6379
      password: redis-password
